name: mm-process-ip-list
description: Aggregate and collapse lists of IP addresses/CIDR
author: Luigi Mori
inputs:
  list:
    required: true
    description: filenames of lists to aggregate (using glob)
  followSymbolicLinks:
    required: false
    description: 'Indicates whether to follow symbolic links'
    default: true
  initval:
    required: false
    description: filename of the list to aggregate list to
  filter:
    required: false
    description: filename of the list to be used to filter entries out
  filterReservedIPs:
    required: false
    description: if set, the IPs matching reserved IPs will be removed from the result
    default: false
  minIPv6Mask:
    required: false
    description: "minimum IPv6 mask to accept (default: 8)"
    default: "8"
  minIPv4Mask:
    required: false
    description: "minimum IPv4 mask to accept (default: 8)"
    default: "8"
  filterInPlace:
    required: false
    description: if set, files matching list pattern are filtered in place and not aggregated
  result:
    required: false
    description: filename to store result into
  delta:
    required: false
    description: filename to store filtered entries
outputs:
  result:
    description: the filename with the resulting list
  delta:
    description: the filename with the filtered entries
runs:
  using: 'node12'
  main: 'dist/index.js'
