name: mm-aggregate-and-collapse-ip
description: Aggregate and collapse lists of IP addresses/CIDR
author: Luigi Mori
inputs:
  lists:
    required: true
    description: filenames of lists to aggregate (using glob)
  follow-symbolic-links:
    required: false
    description: 'Indicates whether to follow symbolic links'
    default: true
  result:
    required: false
    descriptin: filename of the resulting list
    default: ""
  initval:
    required: false
    description: filename of the list to aggregate list to
    default: ""
  op:
    required: false
    description: the operation to perform between list and initval, aggregate or filter
    default: aggregate
outputs:
  result:
    description: the filename with the resulting list
runs:
  using: 'node12'
  main: 'dist/index.js'
